arch:
  - amd64
  - ppc64le
language: go

go:
  - "1.13"
  - "1.14"
  - "1.15"

sudo: false

install:
  - go get -t -d -v ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/modocache/gover
  - go get -u github.com/mattn/goveralls
    # optional dependencies

script:
  - ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
  - ginkgo -tags=gorillamux -r --randomizeSuites --failOnPending --trace --race
  - ginkgo -tags=gingonic -r --randomizeSuites --failOnPending --trace --race
  - ginkgo -tags=echo -r --randomizeSuites --failOnPending --trace --race
  - rm examples/examples.coverprofile
  - bash scripts/fmtpolice
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken gY90SprlNRGmSMl7MgybLreYa05wUXJTU

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9caacfa1bede5e900019
    on_success: change
